server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/retro_game_market
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update